[package]
name = "kurogane-verify"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
kurogane-raft = { path = "../kurogane-raft" }
kurogane-kv = { path = "../kurogane-kv" }
kurogane-sim = { path = "../kurogane-sim" }

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
